language: python
python:
    - "3.8"
    - "3.7"
    - "3.6"
    - "3.5"
sudo: false
env:
    - TOX_ENV=django22
    - TOX_ENV=django30
    - TOX_ENV=djangomaster
matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=djangomaster
install:
    - pip install tox flake8
script:
    - flake8 django_uidfield
    - tox -e $TOX_ENV
