language: python
python:
    - "3.6"
    - "3.5"
    - "2.7"
sudo: false
env:
    - TOX_ENV=django18
    - TOX_ENV=django110
    - TOX_ENV=django111
    - TOX_ENV=djangomaster
matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=djangomaster
install:
    - pip install tox flake8
script:
    - flake8 django_uidfield
    - tox -e $TOX_ENV
