sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO="Django>=2.2,<3.0" DB=sqlite
  - DJANGO="Django>=3.0,<3.1" DB=sqlite
jobs:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1" DB=sqlite
install:
  - export PYTHONPATH=./:$PYTHONPATH
  - pip install -U $DJANGO flake8
script:
  - python setup.py test
